plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
} 

android {
    namespace 'com.skm.guideme'
    compileSdk 35

    defaultConfig {
        applicationId "com.skm.guideme"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    // Google Play Services Location
    //noinspection UseTomlInstead
    implementation 'com.google.android.gms:play-services-location:21.3.0'


    // AndroidX Libraries
    //noinspection UseTomlInstead
    implementation 'androidx.appcompat:appcompat:1.7.1'
    //noinspection UseTomlInstead
    implementation 'com.google.android.material:material:1.12.0'
    implementation libs.activity
    implementation libs.constraintlayout.v221
    implementation libs.cardview
    implementation libs.legacy.support.v13
    implementation libs.annotation
    implementation libs.core

    // OSMDroid and OkHttp
    implementation libs.osmdroid.android
    implementation libs.okhttp
    //noinspection UseTomlInstead
    implementation 'com.android.volley:volley:1.2.1'
    //noinspection UseTomlInstead
    implementation 'com.github.bumptech.glide:glide:4.15.1'
    //noinspection UseTomlInstead
    annotationProcessor 'com.github.bumptech.glide:compiler:4.15.1'



    // Firebase BOM and SDKs
    //noinspection UseTomlInstead
    implementation platform('com.google.firebase:firebase-bom:33.16.0')
    //noinspection UseTomlInstead
    implementation 'com.google.firebase:firebase-auth'
    //noinspection UseTomlInstead
    implementation 'com.google.firebase:firebase-database'
    //noinspection UseTomlInstead
    implementation 'com.google.firebase:firebase-inappmessaging-display:21.0.2'

    // Testing
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}

